---
title: "homework5"
author: "Annika Weber"
date: "2022-11-22"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(tigris)
library(ggplot2)
library(sf)
library(forcats)
```

#import data file and selected only san franscisco  

```{r}
homicides <- read_csv("/Users/annik/homework5/homicide-data.csv")

phoenix_homicides <- homicides %>% 
  filter(city == "Phoenix")

#group all unsolved homicides together in "unsolved" column
phoenix_homicides <- phoenix_homicides %>% 
  mutate(unsolved_homicides = disposition == "Closed without arrest" | 
           disposition == "Open/No arrest") 

#change TRUE and FALSE in "unsolved" column to "Solved" and "Unsolved"
phoenix_homicides <- phoenix_homicides %>% 
  mutate(unsolved_homicides = as_factor(x = unsolved_homicides),
         unsolved_homicides = fct_recode(unsolved_homicides, Solved = "TRUE", 
                                         Unsolved = "FALSE"))

phoenix_homicides %>%
  mutate(victim_race = fct_lump(victim_race, n = 3)) %>%
  count(victim_race)
```

#sf map of phoenix, arizona  

```{r}
az_counties <- counties(state = "AZ", cb = TRUE, class = "sf")


phoenix_blocks <- block_groups("AZ", "Maricopa")

ggplot() +
  geom_sf(data = phoenix_blocks, fill = "darkcyan", alpha = 0.5) 
```
#adding in homicides in phoenix data  

```{r}
phoenix_homicides <- st_as_sf(phoenix_homicides, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)

ggplot() +
  geom_sf(data = phoenix_blocks, fill = "darkcyan", alpha = 0.5) +
  geom_sf(data = phoenix_homicides, aes(colour = city)) + 
  facet_wrap(~ unsolved_homicides) 
  
```

